-- db lab 5 home and class tasks 22k-4080

-- Q1
SELECT e.first_name AS Name, j.job_title, d.department_name AS "Department_Name", e.salary AS Salary FROM employees e 
JOIN departments d ON e.department_id = d.department_id Join JOBS j ON j.JOB_ID = e.JOB_ID
ORDER BY d.department_name ASC;

-- Q2

Select d.department_name FROM EMPLOYEES E, DEPARTMENTS D 
Where E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY d.department_name Having COUNT(E.EMPLOYEE_ID) >= 2;

-- Q3

Select * from employees
Where Salary < (Select Min(Salary) from Employees);

-- Q4

select e.first_name, j.job_title, e.salary*12 as "Annual Salary", d.department_name, l.city From employees e 
Join Departments d On e.department_id = d.department_id Join LOCATIONS l ON d.location_id = l.LOCATION_ID 
join Jobs j ON j.JOB_ID = e.JOB_ID
Where (e.salary*12) >= 60000 AND NOT (j.JOB_TITLE = 'Analyst');

-- Q5

Select * from EMPLOYEES E
WHERE E.EMPLOYEE_ID IN (SELECT MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL);

-- Q6

SELECT D.department_id, D.DEPARTMENT_NAME From DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.department_id = E.department_id
WHERE E.EMPLOYEE_ID IS NULL;

-- Q7

SELECT E.first_name || ' ' || E.LAST_NAME AS "Emp Name", E.SALARY, D.DEPARTMENT_NAME From EMPLOYEES E 
Left JOIN DEPARTMENTS D on E.department_id = D.department_id;

-- Q8

SELECT E.FIRST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY From EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
Join Locations L on L.LOCATION_ID = D.LOCATION_ID
Join Jobs J on J.JOB_ID = E.JOB_ID
WHERE L.STATE_PROVINCE IS NULL;

-- Q9

Select E.* from EMPLOYEES E
LEFT JOIN JOB_HISTORY JH on E.EMPLOYEE_ID = JH.EMPLOYEE_ID
WHERE JH.EMPLOYEE_ID IS NULL;

-- Q10

Select E.first_name || ' ' || E.LAST_NAME AS "US Employee Names" From EMPLOYEES E
Join DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
Join locations L on L.LOCATION_ID = D.LOCATION_ID
WHERE L.COUNTRY_ID = 'US' AND NOT L.STATE_PROVINCE = 'Washington';

-- Q11

Select E.FIRST_NAME, D.DEPARTMENT_NAME From EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);


-- Q12

SELECT E.FIRST_NAME As "Emp Name (job title changed)" From EMPLOYEES E
Join Jobs J On E.JOB_ID = J.JOB_ID
GROUP BY E.FIRST_NAME HAVING COUNT(DISTINCT J.JOB_TITLE) > 1;

-- Q13

SELECT E.first_name As "Emp Name", M.FIRST_NAME AS "MANAGER NAME", E.DEPARTMENT_ID AS "Emp Depart", M.DEPARTMENT_ID AS "Mgr Depart" From EMPLOYEES E
JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE M.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- Q14
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME, L.COUNTRY_ID As "Dept Country" From EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
Join Locations L on L.LOCATION_ID = D.LOCATION_ID;

-- Q15

SELECT E.first_name, D.DEPARTMENT_NAME From EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IN ( SELECT DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID HAVING COUNT(*) > 5 );

-- Q16

SELECT E.first_name As "Emp Name", M.First_name AS "Mgr Name"
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID;

-- Q17

Create Table Employee_Backup As
Select * From EMPLOYEES Where 1=1;

Alter Table Employee_Backup Add Emp_Country Char(2) Default 'US';

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "Emp Name", D.DEPARTMENT_NAME, L.COUNTRY_ID AS "DEPT_COUNTRY", E.Emp_Country FROM EMPLOYEE_Backup E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.COUNTRY_ID != E.Emp_Country;

-- Q18

select E.FIRST_NAME, E.SALARY From EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY > (select AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID)
AND E.SALARY < (select MAX(SALARY) FROM EMPLOYEES);

-- Q19

SELECT E.EMPLOYEE_ID,  JH.DEPARTMENT_ID, D.DEPARTMENT_NAME From EMPLOYEES E
JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
JOIN DEPARTMENTS D ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY E.EMPLOYEE_ID, JH.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(JH.DEPARTMENT_ID) > 1;

-- Q20

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,L.COUNTRY_ID AS "Dept Country ID", C.REGION_ID From EMPLOYEES E
JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
JOIN DEPARTMENTS D ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
Join Countries C ON C.Country_Id = L.COUNTRY_ID
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME,L.COUNTRY_ID, C.REGION_ID
HAVING COUNT(C.REGION_ID) > 1;

-- Q21
-- Region is 2 as all the employees in emp_backup has US set as Country_id
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME, C.REGION_ID From EMPLOYEE_backup E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
Join Countries C ON C.Country_Id = E.EMP_COUNTRY;

--Q22

SELECT E1.FIRST_NAME || ' ' || E1.LAST_NAME AS "Emp with same last name", D1.DEPARTMENT_NAME AS "Dept1", D2.DEPARTMENT_NAME AS "Dept2" From EMPLOYEES E1
JOIN EMPLOYEES E2 ON E1.LAST_NAME = E2.LAST_NAME AND E1.EMPLOYEE_ID != E2.EMPLOYEE_ID
JOIN DEPARTMENTS D1 ON E1.DEPARTMENT_ID = D1.DEPARTMENT_ID
JOIN DEPARTMENTS D2 ON E2.DEPARTMENT_ID = D2.DEPARTMENT_ID
WHERE NOT E1.DEPARTMENT_ID = E2.DEPARTMENT_ID;

-- Q23

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "Emp Names" From EMPLOYEES E
JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME
HAVING COUNT(DISTINCT JH.JOB_ID) > 2;

-- Q24

Select J.JOB_TITLE From JOBS J
LEFT JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID
WHERE E.JOB_ID IS NULL;

-- Q25
--highest salaries from each department
select E.FIRST_NAME || ' ' || E.LAST_NAME AS "Emp Name", E.DEPARTMENT_ID, E.SALARY from EMPLOYEES E
WHERE E.SALARY = (SELECT MAX(E2.SALARY)
FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
)

UNION  --second highest salaries from each department

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "Emp Name", E.DEPARTMENT_ID, E.SALARY from EMPLOYEES E
WHERE E.SALARY = (SELECT MAX(E2.SALARY)
FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
AND E2.SALARY < (SELECT MAX(E3.SALARY)FROM EMPLOYEES E3
WHERE E3.DEPARTMENT_ID = E.DEPARTMENT_ID) )

UNION --third highest salaries from each department

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "Emp Name", E.DEPARTMENT_ID, E.SALARY from EMPLOYEES E
WHERE E.SALARY = ( SELECT MAX(E2.SALARY) FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
AND E2.SALARY < (SELECT MAX(E3.SALARY)
FROM EMPLOYEES E3
WHERE E3.DEPARTMENT_ID = E.DEPARTMENT_ID
AND E3.SALARY < ( SELECT MAX(E4.SALARY)
FROM EMPLOYEES E4
WHERE E4.DEPARTMENT_ID = E.DEPARTMENT_ID) )
);










