-- LAB 01 Home Tasks 22k4080

-- Q1
SELECT * FROM JOBS;

-- Q2

SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY FROM JOBS
WHERE JOB_TITLE LIKE '%President';

-- Q3

SELECT EMPLOYEE_ID,First_name, Last_name, Salary FROM Employees
WHERE Salary > 20000;

-- Q4

--SELECT JOB_ID FROM EMPLOYEES
--WHERE SALARY >=15000;
-- SO we got job_id = 'AD_PRES' OR "AD_VP" that has salary >= 15000
SELECT * FROM JOBS
WHERE JOB_ID IN ('AD_PRES','AD_VP');

-- Q5

SELECT Employee_ID, First_Name, Last_Name, Department_ID FROM EMPLOYEES
WHERE Last_Name LIKE '%Snares%';

-- Q6

SELECT Employee_ID, First_Name, Last_Name, Department_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID=57;

-- Q7

SELECT Phone_number FROM Employees
WHERE DEPARTMENT_ID = 80 AND MANAGER_ID = 100;

-- Q8

SELECT * FROM Employees
WHERE FIRST_NAME LIKE '%John' OR FIRST_NAME LIKE '%Neena' OR FIRST_NAME LIKE '%Lency';


-- Q9

SELECT CITY, COUNTRY_ID FROM Locations
WHERE COUNTRY_ID LIKE '%IT%';

-- Q10

SELECT City, Country_ID FROM LOCATIONS
WHERE COUNTRY_ID NOT IN ('IN','CH');  -- not used LIKE operator because Country ID is already of 2 letters.

-- Q11

SELECT * FROM Jobs
WHERE MIN_SALARY > 8000 AND MIN_SALARY < 15000;

-- Q12

SELECT Phone_number FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90 AND NOT JOB_ID = 'IT_PROG';

-- Q13

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE > '12-Dec-07';

-- Q14

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE > '12-Dec-07' AND DEPARTMENT_ID = 100;

-- Q15

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE > '12-Dec-07' AND NOT DEPARTMENT_ID = 100;

-- Q16

SELECT * FROM EMPLOYEES
WHERE COMMISSION_PCT=0 AND NOT (DEPARTMENT_ID = 100 OR Department_ID = 90);

-- Q17

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE >= '01-Jan-10';

-- Q18
-- Repeated Question
SELECT * FROM Jobs
WHERE MIN_SALARY > 8000 AND MIN_SALARY < 15000;


-- Q19

SELECT FIRST_NAME,LAST_NAME,JOB_ID FROM EMPLOYEES
WHERE (EMPLOYEE_ID > 100 AND EMPLOYEE_ID < 150) AND (DEPARTMENT_ID > 90 AND DEPARTMENT_ID < 100);

-- Q20

SELECT Salary, COMMISSION_PCT, Salary+(commission_pct*salary) as Total_Salary FROM EMPLOYEES;


